#!/bin/bash

if [ -z $WORKSPACE ]
then
	WORKDIR=''
else
	WORKDIR=$WORKSPACE
fi

PID=`ps aef | grep '/usr/bin/python' | grep -v grep | awk '{print ($1)}'`

case "$1" in
    "stop" )
        echo $PID
        kill -9 $PID
        echo "STOOOOOP"
    ;;
    "start" )
        /usr/bin/python $WORKDIR/watchdog.py& > /dev/null
        echo "STAAAAART"
    ;;
    "restart" )
        kill -9 $PID
        /usr/bin/python $WORKDIR/watchdog.py& > /dev/null
        echo "REEEESTAAAART"
    ;;
esac

exit 0
